### ISSUE TITLE
Can't differentiate between empty and zero number field

### ISSUE THREAD

**Issue by mateoeh** [claroty/access_parser#3]
access_parser reports empty number fields as zeroes, so there's no way to tell if the field is actually empty or if it's a literal zero.

Steps to reproduce:
1. Create a database with a non-required number column
2. Leave the field empty in one row, and enter zero in another row
3. Parse the database, observe that both entries are represented by a 0 in the resulting defaultdict

**Comment by ryanavella** [comment]
I think I'm having a related issue. I have a .mdb file with multiple tables, and each table has a column with 64-bit floats. In that column an empty field can produce any of the following:
 * `0`
 * A positive subnormal float with the bits reinterpreted as an integer, e.g. `3866731` (which corresponds to the bit pattern of `1.910419e-317`)
 * `NaN` with bits reinterpreted as an integer, e.g. `-590872253`

I'm not familiar with the .mdb format internals, but my best guess is that each table (or each column) has a specific choice of sentinel value, and no other sentinel value is used. For example, in one of my tables, the value `3866731` appears over 6000 times but `-590872253` is not used once. In another table it is the other way around.

**Comment by SharonBrizinov** [comment]
Yeah there's more research needed on columns attributes (e.g. when it's configured as Empty, Null, Zero, etc).

**Comment by ur1katz** [comment]
I believe the issue was that I did not filter out deleted values from fixed_length values. This should be fixed in the latest version. Please reopen the issue if you have any issues with the fix.
